### ISSUE TITLE
Tabs vs. spaces

### ISSUE THREAD

**Issue by xorgy** [linebender/norad#101]
defcon and FontForge seem to prefer two-space indentation in UFO XML files, but Norad uses tabs.

I see a PR in the past saying that ufonormalizer used a single tab instead, but everything else uses two spaces so I'm a bit confused. From where I stand, more tools use two spaces than one tab, and ufonormalizer is the odd one out. The UFO specification itself has all of its examples set with two spaces per indent as well, which I'm sure contributes to it being a popular option for tools.

**Comment by madig** [comment]
This was a conscious decision since we use ufonormalizer at work. I haven't made up my mind about this.

**Comment by xorgy** [comment]
It just seems unfortunate that ufoNormalizer went this way, because it seems like a very distinct choice in an ecosystem that had already made up its mind. The UFO spec has two space indents on all examples, most tools that author UFOs directly use two spaces, and every UFO that I've seen people work on by hand with a text editor has two-space indents.

This argument seems as old as time, by now, but as far as I can tell, ufoNormalizer sticks out like a sore thumb on this, rather than going with the flow (which is what you would expect them to do) and it causes all sorts of mismatch.

**Comment by cmyr** [comment]
Part of what's going on here, iirc, is that the library we're using to write out the XML uses tabs by default, and configuring it is slightly annoying.

**Comment by xorgy** [comment]
> Part of what's going on here, iirc, is that the library we're using to write out the XML uses tabs by default, and configuring it is slightly annoying.

FWIW, whatever issues you may have had with that in the past, when I tried it (see the PR I attached to this) it seemed to work as expected the first time.

**Comment by xorgy** [comment]
Maybe the right default mode for Norad is to try to detect which of the common conventions each file is observing, and preserve that convention; and then if a file doesn't appear to observe any of the known conventions, simply format it with a default.

**Comment by alerque** [comment]
Detecting the currently used scheme (perhaps even by following hints from things like project EditorConfig settings) sounds like a great step *if* it can be made pretty robust and silent—a best educated guess scenario that doesn't turn up different results on different systems (reproducible).

Also falling back to 2 spaces as the default for projects with to precedent to guess from. I'm okay with campaigning to rid `ufoNormalizer` of its tab addiction.

**Comment by cmyr** [comment]
This is currently blocked for us on the inability of `rust-plist` to allow customization of whitespace; I've [written up a possible patch](https://github.com/ebarnard/rust-plist/pull/61/files) that would make this possible, so we will see how that is received.

**Comment by madig** [comment]
This seems to be implemented as a writer option in master?
