### ISSUE TITLE
Can you please update crates.io?

### ISSUE THREAD

**Issue by ctrlcctrlv** [linebender/norad#118]
I would like some version post-https://github.com/linebender/norad/commit/2233ab4e99d60a58aae9135e4cf704d1517f3b7f on crates.io if possible

**Comment by alerque** [comment]
Agree, frequent crate releases with semver compliance make downstream development much nicer!

That being said @ctrlcctrlv just making sure you're aware you can specify an unreleased Git version in your dependencies...

**Comment by madig** [comment]
I think @cmyr told me he had something coming up before 0.4.0 is tagged?

**Comment by cmyr** [comment]
I'm going to move over the stuff from the pynorad branch that is worth merging independently into some new commits, and also get in a few bits of API breakage and renaming I'd like to do, but I should be able to do a release later today or tomorrow. :)

**Comment by ctrlcctrlv** [comment]
I know @alerque, I'd just like to remove `git` dependencies where possible, and see this as a low-hanging fruit :)

**Comment by cmyr** [comment]
published: https://docs.rs/norad/0.4.0/norad/
