### ISSUE TITLE
Wrapping plist errors

### ISSUE THREAD

**Issue by madig** [linebender/norad#119]
We load plist files at several points during UFO loading. Plist errors are currently very... sparse; their Display impl will print things like `InvalidIntegerString` and that's it. The error also contains line information, but it does not seem accessible from outside the plist crate (https://github.com/ebarnard/rust-plist/issues/60).

I think what's needed is a more extensive `PlistError` akin to `GlifError`?

```rust
/// An error that occurs while parsing a .plist file
#[derive(Debug)]
pub struct PlistError {
    pub path: Option<PathBuf>,
    pub inner: plist::Error,
}
```

And then we need lotsa wrapping everywhere?

Also, writers?

**Comment by cmyr** [comment]
This makes sense to me. Not sure what you mean by "writers", though?

**Comment by madig** [comment]
Another example is e.g. loading a metainfo.plist with a missing `creator field`, the error string from iondrive currently reads 

```txt
    def ctor(path=None):
        import iondrive

        if path is None:
            return ufo_module.Font()
        else:
>           return iondrive.load(ufo_module.objects, str(path))
E           iondrive.IondriveError: Serde("missing field `creator`")
```

**Comment by madig** [comment]
Plist errors are now wrapped and chained and (rough) position information is printed via the error's Display trait.
