### ISSUE TITLE
Glif lib: serialization ends up with unordered keys

### ISSUE THREAD

**Issue by madig** [linebender/norad#127]
The commented out test in https://github.com/linebender/norad/pull/126 fails because the keys of the serialized lib section are unordered when they should be alphabetical with capital letters sorting first. See the referenced sample_period_normalized.glif file.

**Comment by cmyr** [comment]
I've opened https://github.com/ebarnard/rust-plist/pull/61 which includes support for sorting keys, we'll see if that lands.
