### ISSUE TITLE
Update `rust-plist`, use new features

### ISSUE THREAD

**Issue by cmyr** [linebender/norad#145]
There's a new 1.3.1 release. This update lets us make a few desired enhancements:

- [x] we can sort plist keys on write, which is very helpful for reducing unnecessary diff noise
- [x] we can customize whitespace behaviour. I forget what the exact motivation was for this, but I remember we wanted it.
- [x] we can get more information about the position of parse errors https://github.com/ebarnard/rust-plist/pull/64
- [x] we can review the code to do with plist serialization and use Value directly instead of workarounds (e.g. `layerinfo_from_file`?)

**Comment by chrissimpkins** [comment]
These would be great additions Colin.

> we can customize whitespace behaviour. I forget what the exact motivation was for this, but I remember we wanted it.

This limits the diff too.  https://github.com/chrissimpkins/ufo-format-diff/pulls has examples of diffs across commonly used tooling + Noto sources.  Spacing represents the most lines of diff across the source files.

tabs/space formatting in norad discussed in https://github.com/linebender/norad/issues/101

If customization is now possible, it might be useful to allow a library user to choose the type of write spacing that they want (one tab, two tabs, two spaces, four spaces...)?  There seems to be no formatting consensus coming out of discussions on the UFO spec repo and I am guessing that there is even less consensus across the community.  While it is likely more work, it would make this lib more flexible to use *with* other UFO tools out there if this level of customization is possible.

**Comment by cmyr** [comment]
Sounds good, I think should be simple enough to add an alternative "save" function that accepts some additional arguments for things like customizing whitespace.

**Comment by cmyr** [comment]
Okay, here's an annoyance:

sorting dictionary keys requires mutable access to the dictionaries, which means mutable access to the whole font. The `save` function currently takes `&self`, which feels semantically correct; we don't really expect mutation on save.

Some options:

- bite the bullet and just make `save` take `&mut self`.
- Have a separate `&mut self` method, `normalize`, that does the sorting.
- use interior mutability to wrap plists, and sort during `save` without making it `&mut self`
- clone these collections and sort them before saving. (I really wish I had added an `is_sorted` method to `plist::Dictionary` 😞)


One complication with the `normalize` approach involves object libs. Unlike defcon, we store object libs in the actual objects, and then only reinsert them in the parent objects during serialization. We will need to sort after this step anyway, even if we've already called `normalize`.

regrettably, I think that the best approach is going to be making mutable copies of the collections during serialization, and sorting those. This does offend my love of efficiency, but I think it's the best compromise right now.

**Comment by madig** [comment]
We can be efficient if I manage to make a custom plist thing maybe, when I get it done before I die.

**Comment by madig** [comment]
This is done in 0.5, no? Except the position thing?

**Comment by cmyr** [comment]
Yep, just missing the position thing.

**Comment by madig** [comment]
The new plist version supports serialisation of plist types, need to look at where we can drop off workarounds.

**Comment by madig** [comment]
https://github.com/linebender/norad/pull/214 cuts some workaround code.

**Comment by cmyr** [comment]
I think this issue is just about finished? I don't see any other places where we're doing workarounds that can be trivially fixed..

**Comment by madig** [comment]
I forgot if there's more code to be cut. I'll have a look around.

**Comment by cmyr** [comment]
Closing this for now, I'm satisfied.
