### ISSUE TITLE
Allow customizing quote char in xml header

### ISSUE THREAD

**Issue by cmyr** [linebender/norad#156]
- [x] add a `quote_char` method to `WriteOptions`
- [x] When serializing the `.glif`s, (which we serialize manually) write the header to the stream ourselves, using the specified character
- [x] When serializing plists, we don't control writing the header, so we'll have to rewrite. There are options here. All `plist` writing is now handled through a method in `write.rs`. 
  - One option is to write to disk, and then use the unix/windows specific methods to go and overwrite the header in place, before closing the file handle: see [`std::os::unix::fs::FileExt`](http://doc.rust-lang.org/1.53.0/std/os/unix/fs/trait.FileExt.html) and [`std::os::windows::fs::FileExt`](http://doc.rust-lang.org/1.53.0/std/os/windows/fs/trait.FileExt.html); you'll need slightly different impls on either platform.
  - the other option would be to have a custom `Write` type, that would wrap or replace the `BufWriter`; this would intercept the header and replace it, if needed, otherwise forwarding the bytes to the inner writer.

Thinking about this, I think the first option is totally reasonable. The second option is probably marginally more 'efficient', but I don't think it matters; the main thing we want to avoid is closing and reopening all the file handles.

_Originally posted by @cmyr in https://github.com/linebender/norad/issues/148#issuecomment-893514934_

**Comment by chrissimpkins** [comment]
Started

**Comment by chrissimpkins** [comment]
https://github.com/linebender/norad/pull/157

Let me know what you think of the builder enum definition approach for glif files. 

I'll have a look into plist support as you suggested above.

**Comment by chrissimpkins** [comment]
Optional XML declaration single quote serialization is supported in plist files as of 2a962cd5423c897aa32a91b80c7084e8eb01b55b
