### ISSUE TITLE
Use f64 for floating point numbers

### ISSUE THREAD

**Issue by madig** [linebender/norad#164]
Python apparently uses f64 internally for floats but norad uses f32. This leads to vanilla Python code and norad to read the odd floating point coordinate differently (the f32 is upconverted to f64 in PyO3 bindings, changing the precision and making equality testing difficult). Maybe norad should use f64 where the spec talks about floats?

**Comment by cmyr** [comment]
fine by me!

**Comment by madig** [comment]
A designer notified me that this is especially annoying with e.g. guideline angles because they often happen to have a lot of decimal places. When multiple tools read and write those and keep higher precision, norad will always "shorten" them.
