### ISSUE TITLE
Ufo::default() should include all items required by spec

### ISSUE THREAD

**Issue by cmyr** [linebender/norad#19]
Such as, specifically, the default layer. See #17 for discussion.

**Comment by madig** [comment]
Is there a philosophical difference between `default` and `new` here? The latter does include everything required by the spec.

**Comment by cmyr** [comment]
Sometimes new is an alias for default (this is all by convention) but sometimes it can take arguments used in construction. I think it makes sense for us to have a `Default` impl that fills in placeholders, and then `new` can be a way to provide custom initial values?

It's quite possible that this can be closed.

**Comment by madig** [comment]
Makes sense. Then the `new` impl can move over to default and new can go until we have something we want to customize?

**Comment by cmyr** [comment]
yea, or for now we can just have `new` call `default`?
