### ISSUE TITLE
Read / write configuration builder consistency

### ISSUE THREAD

**Issue by chrissimpkins** [linebender/norad#200]
The [`DataRequest` read configuration builder method approach](https://github.com/linebender/norad/blob/5a069856cf5dacf76b20a883e061d36ccc3822f7/src/data_request.rs#L38-L80) returns mutable struct references and works like so:

```rust
let datareq = DataRequest::default().layers(false).kerning(false).to_owned();

let ufo = Font::load_requested_data("path/to/font.ufo", datareq).expect("failed to load");
```

whereas the [`WriteOptions` serialization configuration builder method approach](https://github.com/linebender/norad/blob/6c558317ca727426b99a885600ad3249ffd8b6d6/src/write.rs#L74-L93) returns owned structs:

```rust
let spaces = WriteOptions::default().whitespace("  ");

ufo.save_with_options("path/to/out-font3.ufo", &spaces);
```

`load_requested_data` takes ownership and `save_with_options` borrows.

It might be worth keeping the approach consistent across these config struct builders and read/write implementations?

**Comment by cmyr** [comment]
I agree with this, consistency is nice. I'm not sure if there are any reasons to prefer one to the other? For instance it's possible that the approach that takes ownership increases generated code size?

**Comment by chrissimpkins** [comment]
Any reason not to go with an approach that returns a reference to the config struct from the builder **and** takes a reference parameter where it is used?  This would change both approaches and eliminates the need for users to get involved in ownership issues which may improve ergonomics a bit.

**Comment by chrissimpkins** [comment]
This is what I have in mind:

```rust
let datareq: &DataRequest = DataRequest::default().layers(false).kerning(false);

let ufo = Font::load_requested_data("path/to/font.ufo", datareq).expect("failed to load");
```

```rust
let spaces: &WriteOptions = WriteOptions::default().whitespace("  ");

ufo.save_with_options("path/to/out-font3.ufo", spaces);
```

**Comment by chrissimpkins** [comment]
I went with an approach that builds owned config types and takes either owned or reference parameters in the load/save methods:

https://github.com/linebender/norad/pull/201
