### ISSUE TITLE
ContourPoint: bake smooth attribute into PointType?

### ISSUE THREAD

**Issue by madig** [linebender/norad#202]
Currently, `ContourPoint.smooth` is separate from `typ` but depends on it anyway (smooth must not be set on off-curve points according to the spec). It would be more elegant if if the smooth attribute would be part of PointType?

**Comment by cmyr** [comment]
I agree this isn't great, and if you have a particular design in mind I'm happy to see it. My initial design was simply trying to translate the spec into Rust types as literally as possible.

**Comment by cmyr** [comment]
Thinking about this more, the 'smooth' annotation can apply to Line, Curve, QCurve, and (probably) Move, so I think bundling it in to the enum would be a pain.

I'm inclined to leave this as it is, since it matches the structures in the spec.

**Comment by madig** [comment]
Alright. Maybe for the next major version :)
