### ISSUE TITLE
Image: ensure `file_name` is a bare file name

### ISSUE THREAD

**Issue by madig** [linebender/norad#203]
The images directory must be flat, so the field must be a base file name.

**Comment by cmyr** [comment]
sounds good.

**Comment by cmyr** [comment]
why don't we just validate when loading the image directory that it is flat?

**Comment by madig** [comment]
We do, this is more about making the programmatic API safer to use.

**Comment by cmyr** [comment]
ah okay, I would then make `file_path` private and have a `new` method for `Image` that can error.
