### ISSUE TITLE
Errors: use https://lib.rs/crates/thiserror to reduce description duplication?

### ISSUE THREAD

**Issue by madig** [linebender/norad#204]
The doc updates sorta duplicate the meaning of the error message in the docstring _and_ the Display trait. Should we use thiserror in norad?

**Comment by madig** [comment]
Experimental PR at https://github.com/linebender/norad/pull/211.

**Comment by cmyr** [comment]
looking into this I think it's a good idea, and generates the same code we would get if we were hand-writing things.
