### ISSUE TITLE
Load layers in parallel?

### ISSUE THREAD

**Issue by madig** [linebender/norad#207]
Currently, we load `Layer`s in a `LayerSet` serially and their contents in parallel. This is probably good enough, as I expect only the default layer to contain many glyphs, but the background layer could be big as well.

Need to benchmark.

**Comment by madig** [comment]
@cmyr says:

> yea, since loading the layer contents should use all available resources there isn't a huge win in trying to also serialize layer loading

**Comment by cmyr** [comment]
to elaborate on my thinking: if you have, say, 8 available cores, once you're loading a layer all of your cores should be busy loading glyphs. It's possible there would be some average speedup to parallelizing layer loading I would expect it to be small, and it would add complexity.

**Comment by madig** [comment]
Hm! I do wonder if there is speed to be gained somehow anyway, seeing how today's SSDs work well with random access and have massive bandwidth. A research project for later I suppose.
