### ISSUE TITLE
`Error::ExpectedPlistDictionary` should take key but some code uses paths instead

### ISSUE THREAD

**Issue by madig** [linebender/norad#208]
The error should (?) take a dictionary key, but some functions like `layerinfo_from_file` and `load_lib` put in a stringified path instead. This should be disambiguated; sometimes you expect a plist file containg a dict, sometimes it's a key inside a dict that should contain one.

**Comment by cmyr** [comment]
Removing this from milestone as a non-breaking change.

**Comment by madig** [comment]
The variant is removed by #224
