### ISSUE TITLE
Make public methods in `norad::write` private?

### ISSUE THREAD

**Issue by madig** [linebender/norad#227]
Specifically `write_plist_value_to_file`, `write_xml_to_file` and `write_quote_style public`. I think they are used only internally? @chrissimpkins

**Comment by madig** [comment]
Closed by #228

**Comment by chrissimpkins** [comment]
`Font::load` and `Font::save_with_options` are the only public R/W methods that ufofmt uses in the impl.   I'll check if any of these methods are used in tests.  We'll find a way around it if so.  Thanks for the ping!
