### ISSUE TITLE
Remove `Font.meta.format_version(_minor)` and `Glyph.format` fields?

### ISSUE THREAD

**Issue by madig** [linebender/norad#230]
The current decided-on philosophy is that we support only the latest format versions and try to upgrade older ones. This makes making these versions accessible and changeable pointless and we currently error out on downgrades anyway.

Should they instead be read for loading and upgrading purposes and then discarded? Saving a UFO could take an additional parameter to specify the target version if we find a use-case for that.

This would require keeping up with minor UFO format versions though, otherwise we'd be reading 3.1 UFOs and write out 3.0 ones. But I suppose keeping up would be necessary anyway.

**Comment by cmyr** [comment]
I think we can keep these, since it might be useful to know what the version was when it was loaded? and then if we write it out, we set it ourselves? 🤷
