### ISSUE TITLE
Use of Arc<Glyph>

### ISSUE THREAD

**Issue by cmyr** [linebender/norad#233]
Norad stores `Arc<Glyph>` by default, but this is a slightly weird design choice. Ultimately, the motivation here is runebender, which was the original motivation for this crate; in runebender this is important due to how changes are tracked, but I worry that it might not be that helpful of an API in general.

I'm wondering if I should make the API work with `Glyph` directly, and only use `Arc<Glyph>` when the `druid` feature is enabled? I'd have to think about this a bit more, but I don't think it should complicate things unduly.

**Comment by madig** [comment]
Closed by #234
