### ISSUE TITLE
Downstream request: we need stability guarantees on the items in enums `FontLoadError`, `FontInfoLoadError`, `FontInfoErrorKind`, and `GroupsValidationError` and we want a `norad::Error` struct with a `PartialEq`, not to have to use `std::error::Error` trait objects

### ISSUE THREAD

**Issue by ctrlcctrlv** [linebender/norad#242]
Greetings from downstream MFEK project…

We need stability guarantees on the items in enums `FontLoadError`, `FontInfoLoadError`, `FontInfoErrorKind`, and `GroupsValidationError`, per private chat I had with @cmyr, where I discussed the fact that although an opportunity of sorts was missed regarding using norad for parsing glyphs in MFEK, we don't need to continue this lack of united effort as MFEK moves beyond its glyph editor and towards its font overview (MFEKufo). Indeed, `norad` is already in use by MFEK, but only for minor/marginal commands by `MFEKmetadata`—nothing even user-facing yet (no MFEKglif tool uses Norad, not even Guidelines, Guidelines uses MFEKmetadata in `arbitrary` mode and just feeds it a plist, sidestepping all of Norad's UFO validity checks).

We came to an agreement on how to break the impasse regarding beliefs about UFO validity: enum stability, plus an MFEK-directed and maintained project called `MFEKmakeufovalid` (repo to be @ MFEK/makeufovalid) that will essentially have this for a `main`…

```rust
use norad::{Font as Ufo, DataRequest};
// We don't care if Norad thinks our glyphs are valid as we have our own ideas on glif validity and glifparser has a non-strict mode
let dr = DataRequest::all().layers(false).data(false);
let mut err_count = 0usize;
let mut last_err: Option<norad::Error>;
loop {
    match Ufo::load(&dr) {
        Ok(f) => good_exit(GotUfoLoaded(err_count)),
        Err(norad_e) => {
            if last_err == norad_e { bad_exit(NoradHatedOurFix(norad_e)); }
            last_err = Some(norad_e);
            match crate::fixup::try_norad_fixup(e) {
                Ok(()) => (),
                Err(e) => {
                    bad_exit(OurFixerBroke(norad_e.unwrap(), e))
                }
            }
        }
    }
    err_count += 1;
}
```

This loop would run in a few different modes, not shown above for brevity. Strict-mode, just crash on first Norad error. Eager-mode, eagerly edit the user's UFO, fixing everything we know how to, very destructively (oh, kernings.plist invalid? it's gone now, retry), and finally Cautious-mode, giving the user a choice every time we hit `try_norad_fixup`: this is the error, our planned fix is to do &lt;something>, can we do that destructive thing pretty please? (If not, crash, MFEK can't open your misshapen UFO.)

**Comment by ctrlcctrlv** [comment]
By the way, the level of guarantee I'm asking for is "deprecations instead of removal of old items, no renaming of items, no renaming of structs", but crucially not "no new items" and not "remove the #[non_exhaustive]" flag. If `try_norad_fixup` hits an error kind it doesn't recognize, that will just trigger a `bad_exit`.

**Comment by ctrlcctrlv** [comment]
Oh and now that I think about it, if `norad::Error` were itself a trait e.g.

```rust
trait norad::Error: std::error::Error + PartialEq {}
```

I wouldn't _love_ that but I could live with it. Then your error types can implement this along with the stdlib `Error`. My request remains for a struct, but your project team might not want to make one.

**Comment by cmyr** [comment]
To summarize @ctrlcctrlv's concerns (as I understand them):

In the wild there are lots of invalid UFO files, and MFEK wants to be more relaxed than norad currently is in terms of opening these files.

For the purposes of this discussion I think it's worth talking about the UFO spec in two parts: `fontinfo.plist` and 'everything else'.

### everything else

For everything that is *not* `fontinfo.plist`, my sense is that adhering to the spec is good, and that malformed files should just be fixed. This is the idea that @ctrlcctrlv is asking for support with in this issue; basically by stabalizing our error interface, MFEK can provide a 'ufo fixer' tool that inspects a UFO and fixes any problems encountered, ensuring that when it is passed to norad everything is in okay shape.

Is it worth having a tool like this be part of norad itself? Assuming it is useful I think that this is something to explore at some point, but for the time being I think it makes sense to have this live in MFEK.

### fontinfo.plist

This is a big top-level plist. The spec describes in quite a bit of detail what should be in here, but it is not unreasonable that extra keys or keys with invalid values might turn up here. In norad we currently deserialize this to a concrete struct, and perform all validation at deserialization time. This works, but it does have costs, particularly in terms of code size and compile time. Some quick experiments suggest that our current approach to fontinfo.plist costs up to .5mb in a sample binary, and ~20% of our compilation time.

So... I'm open to trying to figure out a way to be more flexible about this file. What that would look like to *me* would be to deserialize it right to a `Plist`, and then provide methods on that plist for accessing commonly used fields. All methods would be fallible, and there would be a separate `validate` method that would walk through all the keys/values in the plist and check that they were of the expected types.

Ultimately I may be getting too fancy here, and we should just keep things as they are. Especially if there is a good 'ufo fixer' tool that will bring a problem file into compliance with the spec, I think that is a nice approach that makes everyone happy. If this ends up being too annoying for fontinfo, though, we should explore some of the alternatives.

**Comment by ctrlcctrlv** [comment]
Could fontinfo.plist be added to `DataRequest`? Does Norad internally need its information?

**Comment by madig** [comment]
It is typically not touched, only when loading and saving (and when the user calls some method to do something with it).

**Comment by cmyr** [comment]
@madig if in theory we didn't load font info, what else would break? upconversion, probably... anything else?

**Comment by madig** [comment]
Nothing comes to mind... if there is no fontinfo, there is nothing to upconvert. If there is old data in lib.plist, it is upconverted into a fresh fontinfo struct.

**Comment by ctrlcctrlv** [comment]
> Edit: speaking of invalid UFOs, can you point me to some of them? I'm curious.

Open any font on your system, export with FontForge's UFO3 exporter.

Compare to results of sfdLib: https://github.com/aliftype/sfdLib

This UFO is wrong on purpose, to show why I think my idea is good…forcing users to come up w/a bunch of metadata and a font name is too high a burden, so an "MFEK UFO" has no requirement to contain either metainfo.plist or fontinfo.plist (although MFEKinit _does_ write the former now, I'll never require it as I like to drag some glif's into a directory w/a UFO name and call that a "UFO"):

https://github.com/MFEK/glif/tree/master/examples/ImagesExample.ufo

**Comment by ctrlcctrlv** [comment]
Talking about this issue with you all made me finally finish MFEKinit, which ended up being a deeper rabbit hole than expected (see casey/bak#4).

![image](https://user-images.githubusercontent.com/838783/149034628-607bfae0-516c-4621-858d-d2c6d19b221c.png)

```
MFEKinit 1.0.0-beta0
Fredrick R. Brennan <copypaste@kittens.ph>

USAGE:
    MFEKinit [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    glif    Initialize an empty .glif file
    ufo     Initialize an empty .ufo font (Mary, Mary, spec-contrary)
    help    Prints this message or the help of the given subcommand(s)
```

**Comment by ctrlcctrlv** [comment]
Thought of a workaround: I can abuse `Debug` to get a unique string for each error Norad returns and compare those—since I will only be doing comparisons on the same font, it doesn't much matter if things like path names, line numbers, and so on can trip up my detection. Actually it is of quite some benefit, as it allows my loop to try twice. Second may succeed.

Since I care about API ergonomics far less than the authors of this project, I consider this issue closed.

**Comment by cmyr** [comment]
Sorry for being so AWOL fred, I've really lost the battle with my github notifications. Glad you've figured out a solution, and if you're ever blocked on anything please DM me :)
