### ISSUE TITLE
Error out if trying to save UFO version != 3 or glif version != 2

### ISSUE THREAD

**Issue by madig** [linebender/norad#25]
The code currently only supports UFO v3 and glif v2. Converting up- or downwards requires some conversion to happen.

**Comment by cmyr** [comment]
This is iffy. I think I would like to at least load UFO v2, because there's so much of it in the wild; but it would make sense to not save out those files?

This is just pragmatic: it would be nice to load v2 in runebender.

**Comment by madig** [comment]
Okay. I can look into the necessary conversions. I think everything should be upgraded to the highest version internally. Downcasting for serialization can be implemented later :)

**Comment by madig** [comment]
Done already.
