### ISSUE TITLE
Compare validation to ufoLib

### ISSUE THREAD

**Issue by madig** [linebender/norad#26]
Look through https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ufoLib/validators.py to see if we validate everything as ufoLib does.

E.g. check the Postscript blue zone lists, the number of items must be divisible by 2 because they describe start and end points each.

**Comment by madig** [comment]
Or the blue zone list gets a new structure `Zone` so we parse instead of validating.

**Comment by madig** [comment]
I went through fontTools.ufoLib to list all places with an explicit raise:

## `__init__.py`

- _UFOBaseIO
    - _getPlist
        - file is missing
        - file couldn't be read
    - _writePlist
        - data is malformed
- UFOReader
    - `__init__`
        - cannot open ufo path
        - zip contains more than one root folder
        - tried to open fs.base.FS but it's closed
        - wrong type of path
        - (reraise deeper exception)
    - _upConvertKerning
        - data in kerning/groups.plist was changed since it was converted
        - data is malformed
    - _readMetaInfo
        - data is malformed
        - missing formatVersion
        - unsupported format version
    - readGroups
        - data is malformed
    - _readInfo
        - data is malformed
    - readInfo
        - unsupported format version
        - non-functional fontinfo object
    - readKerning
        - data is malformed
    - readLib
        - data is malformed
    - _readLayerContents
        - data is malformed
    - getDefaultLayerName
        - no default layer
    - getGlyphSet
        - cannot find glyph set directory in layercontents
        - cannot open glyph set directory
    - getDataDirectoryListing
        - data is a file insted of a dir
    - getImageDirectoryListing
        - images is a file insted of a dir
    - readData
        - cannot find file
    - readImage
        - format version does not support images dir
        - cannot find file
        - data is malformed
- UFOWriter
    - `__init__`
        - unsupported format version
        - unsupported ufo structure
        - ufo structrue mismatch online/on disk
        - parent dir to write ufo into does not exist
        - zip contains more than one root folder
        - tried to open fs.base.FS but it's closed
        - wrong type of path
        - tried to write downconverted data into higher version ufo
    - copyFromReader
        - reader must be an UFOReader
        - cannot read source data from reader
        - destination data path already exists
    - writeBytesToPath
        - destination path is not a file
    - removePath
        - path does not exist
    - writeGroups
        - data is malformed
    - writeInfo
        - non-functional fontinfo object
    - writeKerning
        - data is malformed
    - writeLib
        - data is malformed
    - writeFeatures
        - not allowed in v1
        - data is malformed
    - writeLayerContents
        - mismatch between layercontents data and passed in layers
    - _findDirectoryForLayerName
        - cannot find layer dir for name
    - getGlyphSet
        - tried to write non-default layer for ufo < v3
        - non-default layer without name
        - unsupported format version
    - _getGlyphSetFormatVersion3
        - another layer is already mapped to the default directory
        - layer name is already mapped to a non default layer
    - renameGlyphSet
        - layer name already exists
        - default layer already exists
    - writeImage
        - unsupported by format version
        - data is malformed
    - removeImage
        - unsupported by format version
    - copyImageFromReader   
        - unsupported by format version
- _sniffFileStructure
    - unknown structure
    - path not found
- validateInfoVersion2Data
    - data is malformed
- validateInfoVersion3Data
    - data is malformed
- convertFontInfoValueForAttributeFromVersion1ToVersion2
    - data is malformed
- _convertFontInfoDataVersion1ToVersion2
    - data is malformed
- _convertFontInfoDataVersion2ToVersion1
    - data is malformed
- convertFontInfoValueForAttributeFromVersion2ToVersion3
    - data is malformed

## filenames.py

- userNameToFileName
    - input name of wrong type
- handleClash2
    - cannot find unique name

## glifLib.py

- GlyphSet
    - `__init__`
        - unsupported format version
        - no "glyphs" directory
        - tried to open fs.base.FS but it's closed
        - wrong type of path
        - contents.plist is missing
    - rebuildContents
        - contents.plist references non-existent file
        - data is malformed
    - readLayerInfo
        - data is malformed
        - non-functional layerinfo object
    - writeLayerInfo
        - unsupported by format version
        - non-functional layerinfo object
    - getGLIF
        - file does not exist
    - writeGlyph
        - unsupported format version
        - unsupported format version in ufo format version
    - __getitem__
        - glyph does not exist
- readGlyphFromString
    - unsupported format version
- _writeGlyphToBytes
    - unsupported format version
    - data (name) is malformed or empty
- _writeAdvance
    - data is malformed
- _writeUnicodes
    - data is malformed
- _writeNote
    - data is malformed
- _writeImage
    - data is malformed
- _writeGuidelines
    - data is malformed
    - duplicate identifier
- _writeAnchorsFormat1
    - data is malformed
- _writeAnchors
    - data is malformed
    - duplicate identifier
- _writeLib
    - data is malformed
- validateLayerInfoVersion3Data
    - unknown name for attribute
    - invalid value for attribute
- _glifTreeFromFile
    - <glyph> is not root element
    - <glyph> contains text
- _glifTreeFromString
    - <glyph> is not root element
    - <glyph> contains text
- _readGlyphFromTree
    - unspecified format version
    - unsupported format version
    - forbidden format version
    - reading not implemented for format version
- _readGlyphFromTreeFormat1
    - outline element occurs more than once
    - outline element contains unknown attribute
    - outline element contains text
    - advance element occurs more than once
    - unicode hex value cannot be parsed
    - note element occurs more than once
    - lib element occurs more than once
    - unknown element
- _readGlyphFromTreeFormat2
    - outline element occurs more than once
    - outline element contains unknown attribute 
    - outline element contains text
    - advance element occurs more than once
    - unicode hex value cannot be parsed
    - guideline element contains children
    - anchor element contains children
    - image element occurs more than once
    - image element contains children
    - note element occurs more than once
    - lib element occurs more than once
    - unknown element
    - guideline data is malformed
    - anchor data is malformed
- _readName
    - name is empty
- _readLib
    - data is malformed
- _readImage
    - image data is malformed
- buildOutlineFormat1
    - outline element contains unknown children
    - anchor v1 data is malformed
- _buildAnchorFormat1
    - missing x or y attribute
- _buildOutlineContourFormat1
    - unknown attributes
- _buildOutlineComponentFormat1
    - component element contains children
    - component element contains unknown attributes
    - component element is missing base attribute
- buildOutlineFormat2
    - outline element contains unknown children
- _buildOutlineContourFormat2
    - unknown attributes
    - duplicate identifier
    - invalid identifier
- _buildOutlinePointsFormat2
    - duplicate identifier
    - invalid identifier
- _buildOutlineComponentFormat2
    - component element contains children
    - component element contains unknown attributes
    - component element is missing base attribute
    - duplicate identifier
    - invalid identifier
- _validateAndMassagePointStructures
    - contour element contains unknown children
    - point element contains unknown attributes
    - point element contains children
    - point is missing x or y attribute
    - point has unknown type
    - move occurs after the first point
    - unknown point smooth attribute
    - smooth attribute set on off-curve point
    - move point has off-curve point
    - line point has off-curve point
    - curve point has too many off-curve points
- _number
    - cannot parse number
- GLIFPointPen
    - beginPath
        - duplicate identifier
        - invalid identifier
    - endPath
        - trailing off-curve points
    - addPoint
        - coordinates have wrong type
        - move occurs after the first point
        - move or line point has off-curve point
        - curve point has too many off-curve points
        - smooth attribute set on off-curve point
        - duplicate identifier
        - invalid identifier
    - addComponent
        - coordinates have wrong type
        - duplicate identifier
        - invalid identifier

## UFO3_test.py

No raise, but should a layer directory not listed in layercontents.plist raise an error?

**Comment by madig** [comment]
I think that we only skip on "outline element contains unknown attribute", everything else (unless I'm forgetting something) is covered or not applicable to our Rust code.

**Comment by madig** [comment]
I believe we do everything except the following:

- on write: the font lib dict key "public.glyphOrder" must be a sequence of strings
- on write: the glyph lib dict key "public.markColor" must be a valid color string
- some fontinfo Postscript values must be lists of pairs

Much of the rest is, I think, not applicable due to Rust's type system and existing checking code.

**Comment by cmyr** [comment]
Hmm, I really don't have strong feelings about this. I would only worry about validation if we were ever using these keys, and expecting them to have some known format? If we don't touch them, we can leave it to the client to handle this.

**Comment by madig** [comment]
Alright, sounds fair. I'm going to go over the list one more time, but then I think we can close it for now with #249.
