### ISSUE TITLE
Feature idea: deleting glyphs from `Font`

### ISSUE THREAD

**Issue by RickyDaMa** [linebender/norad#271]
Hi there!

I'm interested in being able to delete a glyph from a UFO/`Font`. Would you consider accepting a method like this in a PR?

One immediate issue that comes to mind is that deleting glyphs can potentially lead to a dangling reference in the feature file, which is messy. Cleaning this up as part of the method would require loading and parsing the feature file - definitely outside the responsibility of the `Font` struct. Would you consider it acceptable to leave this dangling reference, do you have an alternative solution to suggest, or would that be a dealbreaker for the PR/feature?

**Comment by belluzj** [comment]
I would say that the basic API of deleting a glyph from a UFO's layer, which achieves: delete the contents.plist entry for that glyph + the .glif file, should be straightforward to add.

A more "comprehensive" API that would also remove references to that glyph from various places such as kerning, groups, feature file, public.glyphOrder etc. might be out of scope and way more complicated and subject to preferences from users of this library.

**Comment by madig** [comment]
A `Layer::remove_glyph` method exists already :)
