### ISSUE TITLE
Use font-types in norad?

### ISSUE THREAD

**Issue by rsheeter** [linebender/norad#276]
From https://github.com/linebender/norad/pull/272#discussion_r1020591640.

+1 from me, only concern is I think we want any font-types dependence on serde to be optional.

**Comment by cmyr** [comment]
I looked into this quickly and it's not totally obvious that there are many places this would make sense. The obvious one is the `Tag` type in designspaces, and maybe the various table-specific fields on `fontinfo.plist`; the problem with this second case is that while these do map to specific values in the tables, the UFO spec often specifies them in different formats; for instance the `openTypeHeadCreated` field is a string, not a `LongDateTime`.

**Comment by madig** [comment]
I think UFO is using more general types on purpose, because the original goal was to encompass more than OpenType.

**Comment by cmyr** [comment]
That's a very reasonable goal I think.
