### ISSUE TITLE
FontLoadErrors are "very large"

### ISSUE THREAD

**Issue by simoncozens** [linebender/norad#277]
cargo clippy is upset that:

```
warning: the `Err`-variant returned from this function is very large

356 |     ) -> Result<norad::Font, norad::error::FontLoadError> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 152 bytes
```

**Comment by cmyr** [comment]
Are you on master or a release? I believe this was fixed in fdc5cdb.

**Comment by simoncozens** [comment]
Ah, cool. I’m using the latest release - is another one coming soon or should I switch to master?

**Comment by cmyr** [comment]
there will be one soon, to include the design space support.
