### ISSUE TITLE
Mid/long-term vision for Norad in the current font lib ecosystem

### ISSUE THREAD

**Issue by madig** [linebender/norad#30]
Colin asked me to write down what I would like norad to be. In short, I would like to see it as the entry point into the font compilation pipeline.

Why the entry point? Because the process of compiling a font needs a library that can construct general SFNT tables and compile AFDKO feature files and possibly other formats into OpenType Layout tables, which are both much bigger efforts than writing the handling of input formats. It's a start. For the rest, a Python bridge into fontTools and friends is needed.

Norad already almost covers the UFOv3 input format. It should also be able to read and write Designspace files, which hold UFOs as children.

There's roughly two things you can do with a Designspace: make instances or pass it to `fontTools.varLib` to make a variable font. Making instances can be implemented in Norad, but it needs to call into Python at a few points. Variable fonts should be left to fontTools for now.

Instances: In Python, the `fontmake.instantiator` module loads a Designspace and wraps all the master data (glyphs, kerning values, fontinfo values, ...) into fontMath objects, which implement arithmetic on them. It then uses `fontTools.varLib` to compute how to mix the masters to arrive at an instance, which is applied to the fontMath wrappers. The interpolated result is put into an instance UFO object and passed on or written to disk.

So, these pieces of code would be neccessary to implement in Rust:
- My Designspace reader and writer implementation: https://gist.github.com/madig/5a3e13894f75287272a06983052b4322 or the original designspaceLib.
- My instantiator module: https://github.com/googlefonts/fontmake/blob/master/Lib/fontmake/instantiator.py.
- fontMath
- The part of varLib that computes interpolation factors?
- Complicating factor: How to wire up Rust code to behave like the Python libs they are pretending to be?

The biggest gains I would expect with this are:
1. SPEED.
2. Potentially higher correctness, as Rust forces error management on you.

**Comment by ctrlcctrlv** [comment]
> Complicating factor: How to wire up Rust code to behave like the Python libs they are pretending to be?

C ABI, of course. :-) Rust is perfectly usable from Python.

**Comment by madig** [comment]
I had the idea to use one of the Rust/Python bridging libraries to make a ufoLib work-alike so one can plug Norad into existing Python libraries.

**Comment by madig** [comment]
I think this can be closed for now. I decided to use https://github.com/simoncozens/iondrive for the Python bridge.
