### ISSUE TITLE
`LayerSet` is ordered when it is not implied or documented as such

### ISSUE THREAD

**Issue by RickyDaMa** [linebender/norad#326]
A set is traditionally unordered, so one would expect `LayerSet` to be unordered. The fact that it is actually ordered wouldn't matter if it wasn't for the fact that its `PartialEq` implementation relies on ordering

This came up as a frustrating footgun while I was fixing a test within a bigger project, and until I questioned norad and looked into its internals I didn't know why I could compare individual layers and have them all be equal, but have two mismatching layer sets

Suggested solutions:
1. Making `LayerSet` actually unordered (though I daresay there's some reason why it is ordered)
2. Documenting that `LayerSet` is ordered, preferably changing it's name to not mislead
3. Make the `PartialEq` implementation be order-insensitive. This may be challenging without incurring allocations

**Comment by anthrotype** [comment]
I agree LayerSet is a bit of a misnomer.. layers in UFO are in fact _ordered_, layercontents.plist is an array of (layer_dir_name, layer_name) so the the order does matter.

> This list also defines the order of the layers from top to bottom.

https://unifiedfontobject.org/versions/ufo3/layercontents.plist/

**Comment by anthrotype** [comment]
although it is true that in ufoLib2 the `LayeSet.__eq__` (automatically generated by attrs for us) only compares the inner `_layers` attribute which in turn is defined as a `Dict[str, Layer]` so... python isn't actually considering the (insertion) order of the dicts when comparing them. Maybe it should, if LayerSet is supposed to model the layercontents.plist.

**Comment by anthrotype** [comment]
I'd vote for

> 2. Documenting that LayerSet is ordered, preferably changing it's name to not mislead

The "LayerSet" name probably comes from ufoLib2, which in turn inherited it from defcon, and the latter probably from robofab? Each successive iteration of the ancestral UFO API attempted somehow to maintain the old names for backward compatibility sake so they can be used as drop-in replacements.
It's probably too late for a name change.

**Comment by cmyr** [comment]
Just to add my two cents: conceptually the only strong implication of the term 'set', to me, is that items are unique. The fact that *hash*sets offer no ordering guarantees is an implementation detail, but it is entirely reasonable for sets to use a consistent ordering, such as is the case with the `BTreeSet` in rust's `std`.

I definitely agree that it would be nice to mention this in the docs.

**Comment by rsheeter** [comment]
Naming is the hardest part ;)

>  if LayerSet is supposed to model the layercontents.plist

Naively, might we call it LayerContents to make this relationship more explicit?
