### ISSUE TITLE
Designspaces: support deserialising empty condition sets

### ISSUE THREAD

**Issue by RickyDaMa** [linebender/norad#327]
Error:
> failed to deserialize designspace: missing field `condition`

Debug representation:
```
DeError(                            
    Custom(                         
        "missing field `condition`",
    ),                              
)
```

<details><summary>Example reproducer: modded Mutator Sans designspace</summary>
<p>

```xml
<?xml version='1.0' encoding='utf-8'?>
<designspace format="4.0">
    <axes>
        <axis default="0" maximum="1000" minimum="0" name="weight" tag="wght" />
    </axes>
    <sources>
        <source familyname="MutatorMathTest" filename="MutatorSansLightCondensed.ufo" stylename="LightCondensed">
            <lib copy="1" />
            <groups copy="1" />
            <features copy="1" />
            <info copy="1" />
            <location>
                <dimension name="weight" xvalue="0" />
            </location>
        </source>
        <source familyname="MutatorMathTest" filename="MutatorSansBoldCondensed.ufo" stylename="BoldCondensed">
            <location>
                <dimension name="weight" xvalue="1000" />
            </location>
        </source>
    </sources>
    <instances>
        <instance familyname="MutatorMathTest" filename="instances/Extrapolated.ufo" stylename="Extrapolated">
            <location>
                <dimension name="weight" xvalue="2000" />
            </location>
            <kerning />
            <info />
        </instance>
    </instances>
    <rules>
        <rule>
            <conditionset></conditionset>
        </rule>
    </rules>
</designspace>
```

</p>
</details> 

Yes the fields could just be removed, but I also don't think this should be egregious enough to fail deserialisation entirely

**Comment by cmyr** [comment]
an empty conditionset *is* invalid, per the spec (it "Contains one or more <condition> elements."). We could add custom logic to allow parsing it if empty and then discard it, if this is particularly common in the wild.

Is this getting written by designspaceLib? if so we should also open an issue there, as this looks like a spec violation.

**Comment by rsheeter** [comment]
If it turns out desigbspacelib does this then it might be we should update
the spec to match the implementation, check with Cosimo.

**Comment by belluzj** [comment]
The implementation of designspace v5 to split one big designspace into smaller ones may emit empty conditionsets when a given rule should always be active in the sub-designspace that we're emitting. See: https://github.com/fonttools/fonttools/blob/98242634c45cf4ca9f8aff6fd059de9dcf734471/Lib/fontTools/designspaceLib/split.py#L402

![image](https://github.com/linebender/norad/assets/3616772/80dc0d27-754e-436d-87cc-5bb4ed68a5d5)

**Comment by anthrotype** [comment]
cool thanks, makes sense. So I imagine that building off that will generate a VF with a FeatureVariationRecord containing an empty (always-on) ConditionSet. If somebody can give that a try and confirm that's the case, we can update the DesignSpace spec to match this. And norad as well.
