### ISSUE TITLE
updating to quick-xml 0.31 breaks our lib deserialization

### ISSUE THREAD

**Issue by cmyr** [linebender/norad#330]
this has been an unexpected rabbit hole, but basically: if we want to upgrade to the latest quick-xml, we need to figure out how to get our custom deserialization code working again, which I've just burnt a couple of hours on.

**Comment by cmyr** [comment]
it would reduce upstream duplication of dependencies, but isn't necessary. I'll spend a bit more time today and see if I'm close to having a fix, otherwise we can defer.

**Comment by cmyr** [comment]
I have not continued trying to hack at this, feel free to take a look if you're feeling adventurous/masochistic 💁‍♂️

**Comment by rsheeter** [comment]
Unable to update quick-xml seems like a bad state to stall in :(

quick-xml does seem to have fiddled with the relevant parts, for example https://github.com/tafia/quick-xml/commit/b7787b0fa35fd8dd0279271430db868776172594 looked suspicious to me. Sadly reverting it did not fix the problem. My default assumption would be it's a problem with our deserializer, but I couldn't immediately spot anything suspicious.

IMHO a good next step would be to try to narrow it down to a simpler reproduction than norad using plist and quick-xml together. For example, can we make a standalone repo with a simple data structure that fails on quick-xml 0.31.0 and works on 0.30.0? - if so, we should report it as a bug.

**Comment by rsheeter** [comment]
Copying from IM to here so it doesn't get lost, another path would be to use quick-xml but not serde, just handwrite an event handling parser in The Old Style. Tiresome but simple and unlikely to break.

@cmyr mentioned glif files already work this way.
