### ISSUE TITLE
Improving disk I/O performance on Windows

### ISSUE THREAD

**Issue by RickyDaMa** [linebender/norad#334]
Full disclosure, this is basically an advert for a little crate I wrote over the weekend: [`close_already`](https://github.com/alpha-tango-kilo/close_already)

In short, by using my crate (under 1000 SLoC including the two transitive dependencies*) **I was able to speed up norad (without rayon) writing a big UFO to disk by 67%**, and a further ~10% when the rayon feature was enabled (despite a suboptimal implementation with conflicting threadpools). You can read more about how this works in the crate's README

I still need to benchmark read performance for exact numbers, but there should also be performance improvements there as well

I've made the library work as a no-op on other compile targets and tried to keep it simple & uninvasive to integrate, so I was wondering if `norad` would be interested in a PR to show what this looks like?

\* EDIT: when using the default `backend-threadpool`

**Comment by cmyr** [comment]
So this is tricky, and it's a problem I've run into before.

Basically: cargo features are intended to be [*additive*](https://doc.rust-lang.org/cargo/reference/features.html?highlight=additive#feature-unification). That is to say, a feature is not intended to be used to switch between impls, and enabling a feature should never 'turn off' any existing code, only 'turn on' something.

One possible solution would be to allow your crate to compile two backends, but have one of them just be unused, if rayon is available? We'll still compile it, but the generated code should at least be pruned during dead code analysis. (I believe that this is the conclusion you've reached anyway?)

There's also definitely an argument for just always enabling rayon in norad. I have historically tried to be judicious in my use of dependencies, and that is the rationale for having rayon behind a feature; there are patterns of using norad where you aren't relying on us to load everything, in which case rayon would be unnecessary, but maybe I could also just relax and leave it on, if that would be a good simplification.
