### ISSUE TITLE
crash when saving after renaming a glyph

### ISSUE THREAD

**Issue by cmyr** [linebender/norad#46]
Not super surprising, never really tried to exercise any of this. 

`thread 'main' panicked at 'all glyphs in contents must exist.', ~/.cargo/git/checkouts/norad-38f495afcd82c43a/0a18f6c/src/layer.rs:70:25`

**Comment by cmyr** [comment]
we aren't updating a layer's contents on glyph deletion 🤷

**Comment by madig** [comment]
Renaming glyphs is a huge ball of hair. I'm working on an internal tool to do that right now. Not only do you need to rename the glyph (and handle overwrites somehow), you also have to do it in all groups and kerning pairs, ideally also in the feature file plus the publicly known lib keys.

**Comment by cmyr** [comment]
right, yea. hmhm, another thing for the list. ;)
