### ISSUE TITLE
How to implement public.objectLibs

### ISSUE THREAD

**Issue by madig** [linebender/norad#70]
They glif and font-level key https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#publicobjectlibs is meant to provide identifiable objects (anchors, guidelines, components, outlines, contours, points) with their own `lib`. Before, there was only the global lib.plist and the glif-specific embedded lib. The object lib is stored separately from the object because putting it where it belongs would require a new format plus version bump, that's reserved for UFO v4. Global guideline libs are stored in lib.plist, everything glyph-specific in the embedded lib there.

In ufoLib2, this is implemented in https://github.com/fonttools/ufoLib2/pull/113. The PR added the new methods `Font.objectLib(obj: Identifiable)` and `Glyph.objectLib(obj: Identifiable)`, where `Identifiable` is anything with an `identifier` attribute. The methods look at the object identifier (and assign a new UUIDv4 one if there isn't one already) and then fetch the dictionary in the font's or glyph's lib keyed to that identifier (or create and return a new one). We specifically avoided just adding a lib to the objects themselves, as would be ideal, because then you'd have a chance of font/glyph lib and object lib getting out of sync unless you store a back-reference to the containing font or glyph object and we didn't want that in ufoLib2. What if you wrote something to a glyph's objectLibs that was different from what the actual object had? Which would win at serialization time? What to do with the losing data? The `(Glyph|Font).objectLib(obj: Identifiable)` approach keeps the libs where they are saved and free of conflicts.

So, how to do this for Norad? There is no way yet to have a trait that just has a struct field in it, so you'd need a getter and setter.. and probably take the `pub` away from identifiers? Haven't looked into that, not sure how it impacts ergonomics... Maybe there's a better approach? Since the `objectLib` approach above modifies both object and containing lib, it is essentially a `fn object_lib(&mut self, &mut Identifiable) -> &mut Dictionary`, not sure how that vibes with the borrow checker.

**Comment by cmyr** [comment]
The part that I'm unclear about is the part where we create a new identifier if one is missing.

 Thinking about this a bit more, I think that our *ideal* solution is to store this lib data in the individual component/contour/anchor etc as you describe, and then write it out to the lib (and add missing identifiers) only when we serialize. It is true that if the library user clones an outline and mutates the lib this will not be reflected in the glyph's copy, but this is already true of any other mutation the user makes to the outline, so this doesn't feel like a particular concern?

**Comment by madig** [comment]
Hm! I didn't think about cloning individual things, just whole glyphs. All identifiable structs then need their own clone method that assigns a new identifier if it's Some.

I'm just trying to keep edge cases under control. My first impl for ufoLib2 did that actually. On read, it would scour the glif and global lib and extract `public.objectLibs` and shove the content into the identified objects and then remove the lib key. On serialization, it would simply make a new `public.objectLibs` and overwrite whatever was there before. It worked, but was a bit "magic"...

The `objectLib` approach seems complicated though because we're missing traits for struct fields. Putting `get_lib` methods on the structs themselves still is not ergonomic because then you need to take either Font or Glyph... or a ref to their lib. And even then, you need to handle dictionary edge cases. Not nice.

**Comment by madig** [comment]
Implemented with #71.
