### ISSUE TITLE
Glyph: remove `name` field?

### ISSUE THREAD

**Issue by madig** [linebender/norad#73]
The format saves the glyph name in the layer _and_ in the glyph itself. The spec used to say (before the redesign) that this was redundant and may be changed in the next version of the format.

Removing the name would make it possible to implement `Default` on `Glyph`.

**Comment by cmyr** [comment]
So in runebender, as mentioned, we have a sort of 'check out/check in' way of handling glyphs. For this to work we need some way of associating the glyph object with the source layers.

We also regularly want to display the name in places where we only have access to the glyph.

So... I'm not sure?

**Comment by madig** [comment]
Hm. If we want Glyph to potentially be used as stand-alone things, the name attribute can stay. We already make sure to overwrite the glyph name with whatever is in contents.plist at layer load time.
