### ISSUE TITLE
unexpected 'data' field in some glyphs?

### ISSUE THREAD

**Issue by cmyr** [linebender/norad#83]
Playing around loading various UFOs into runebender and I hit a panic in the [following glyph](https://github.com/googlefonts/kreon/blob/467d2f024dcc338b941de2ed1e6e5eaafc189ceb/sources/non-variable-legacy-sources/Kreon-Regular.ufo/glyphs/bar.glif):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph name="bar" format="1">
  <advance width="247"/>
  <unicode hex="007C"/>
  <outline>
    <contour>
      <point x="169" y="-214" type="line" name="hr00"/>
      <point x="169" y="694" type="line"/>
      <point x="78" y="694" type="line"/>
      <point x="78" y="-214" type="line"/>
    </contour>
  </outline>
  <lib>
  <dict>
  <key>com.typemytype.robofont.mark</key>
  <array>
    <real>1</real>
    <real>0.6</real>
    <real>0.751</real>
    <real>1</real>
  </array>
  <key>com.adobe.type.autohint</key>
  <data>
  <hintSetList>
    <hintset pointTag="hr00">
      <hstem pos="-193" width="-21" />
      <hstem pos="694" width="-20" />
      <vstem pos="78" width="91" />
    </hintset>
  </hintSetList>
  </data>
  </dict>
  </lib>
</glyph>
```

The issue here is the `<data>` tag; we don't seem to now what to do with it. I'm really not sure what we *should* be doing with it; plist expects `<data>` elements to contain b64 encoded data, and this is just... arbitrary xml? Is this common in the wild? Clearly other tooling supports this somehow.

**Comment by madig** [comment]
I think this is some kind of stupidity inserted by old tooling, possibly older psautohint. I remember reading something in the Fontlab 7 release notes about how they pledge not to do that anymore going forward but forgot the context.

It is obviously invalid data but the plist parsers elsewhere seem to be hand written to not care.

**Comment by madig** [comment]
I'd say close this? I currently don't see the use of supporting it.
