### ISSUE TITLE
Ensure default layer is always present

### ISSUE THREAD

**Issue by madig** [linebender/norad#89]
The layer list is currently just a Vec, maybe it should be a wrapper struct that ensures the default layer is always present. This can also enforce that the name `public.default` is only used for the default layer.

Once this is ensured, `Ufo::get_default_layer` can return `&Layer` instead of an `Option`.

**Comment by cmyr** [comment]
we could also just always create the default layer as needed when we initialize the font?

**Comment by madig** [comment]
That would require &mut self access in get_default_layer?

**Comment by cmyr** [comment]
not when we first access the layer, when we create the font object.

**Comment by madig** [comment]
But you can delete the layer afterwards and then get_default_layer needs &mut to put it back? 🤔

**Comment by cmyr** [comment]
ah I forgot that `layers` is currently public.

**Comment by madig** [comment]
I suppose we can make it private and provide the `Font` methods `new_layer(name: String)`, `remove_layer(name: &str) -> bool` (refuses to remove default layer and returns `false`) and the usual `get_layer(_mut)(name: &str)`, `get_default_layer(_mut)()`, `iter_layer(_mut)`.
