### ISSUE TITLE
Glyph: get Vecs out of Options?

### ISSUE THREAD

**Issue by madig** [linebender/norad#92]
Currently, contours, components, anchors, codepoints and guidelines are Vecs hidden behind an `Option`, which seems to be because they allow for non-existence of attributes in a glif file. This leads to code like 

```rust
fn move_glyph(glyph: &mut Glyph, delta: f32) {
    let Some(outline) = &mut glyph.outline {
        // ...
    }
}
```

which I don't find especially, uh, ergonomic? Same goes for  anchors, etc. I'd rather have a 

```rust
pub struct Glyph {
    pub name: GlyphName,
    pub format: GlifVersion,
    pub advance: Option<Advance>,
    pub codepoints: Vec<char>,
    pub note: Option<String>,
    pub guidelines: Vec<Guideline>,
    pub anchors: Vec<Anchor>,
    pub contours: Vec<Contour>,
    pub components: Vec<Component>,
    pub image: Option<Image>,
    pub lib: Option<Plist>,
}
```

Since empty Vecs can just not be serialized (and don't alloc until they have one member), I don't think making them optional holds semantic value? Same for `lib` maybe?

Related to https://github.com/linebender/norad/issues/27.

**Comment by cmyr** [comment]
Yes, it's gross. my intention was to losslessly adhere to the UFO spec, and represent all fields that were optional as `Option<_>` on the rust code. I'm not sure if this matters nor not? The way that it might matter is for round-tripping, if we wanted to preserve empty collections or something.

I defer to you, here; if you think it makes sense to use an empty vec to represent a missing field, and not serialize empty vecs, that sounds good to me.

**Comment by madig** [comment]
- codepoints: defined by a full element, so can't be an empty collection
- guidelines: same
- anchors: same
- components: same
- contours: can have empty collection, but see https://github.com/unified-font-object/ufo-spec/issues/150

FWIW, ufoLib2 and defcon use empty lists for the above.

**Comment by cmyr** [comment]
Happy to see this change, it will be a nice ergonomics improvement.

**Comment by madig** [comment]
I just noticed: in the same vein, advance width and height are kept behind Option. The spec says https://unifiedfontobject.org/versions/ufo3/glyphs/glif/#advance, i.e. both could be regular fields defaulting to 0.

**Comment by cmyr** [comment]
this also sounds good, the only reason these various things are awkward is because i did not feel knowledgeable enough to take any liberties.

**Comment by madig** [comment]
Good thing you now have extreme prejudice on your team.
