### ISSUE TITLE
Revamp GlyphBuilder

### ISSUE THREAD

**Issue by madig** [linebender/norad#95]
It is now easier to outfit a Glyph without all the `Option`s, so maybe it's time to revisit GlyphBuilder. It currently checks that:

1. ... all identifiers we use are unique
2. ... some methods are not called for format 1 glyphs (e.g. adding guidelines)
3. ... some methods are not called more than once

The last point is due to glif file parsing, some elements are supposed to occur at most once. I think I should move that logic back into the glif parser and turn `GlyphBuilder` into a simpler general builder that just ensures all identifiers are unique and only format-appropriate methods are called :thinking:  If there's a better way to do that, the builder can maybe go away completely. As long as there is no other use-case for the builder, the once-checking may as well stay, though.

Semi-related: The split GlyphBuilder <-> OutlineBuilder is somewhat problematic in that there needs to be a handover point for components, contours and identifiers (the latter need to be merged over so later builder commands can check against outline identifiers). If the builders are to be exposed to the outside, it would currently also require to expose the `Outline` intermediate struct for handover (making `OutlineBuilder` return components, contours and identifiers separately triggers clippy). This is... suboptimal. Maybe OutlineBuilder should be merged back into Glyphbuilder?

**Comment by cmyr** [comment]
I think this bit of code is now pretty much all yours, so I'm happy to defer to your judgement. If there's anything in particular you want to talk through I'm happy to do that? I agree that a single `GlyphBuilder` type might make the most sense.

**Comment by madig** [comment]
Running into this again while trying to revamp the error hierarchy in #224. There is a bit of a concern sharing going on between `(Glyph|Outline)Builder` and the `GlifParser`, e.g. the aforementioned v1 checking, that makes clear error separation difficult.

**Comment by madig** [comment]
Also, `GlyphBuilder.finish()` needs no Result return type.

**Comment by madig** [comment]
Thinking about it a bit more, maybe the not-called-more-than-once logic should also be handled while parsing, because it is part of the UFO XML specification. I'm not sure if there's a benefit to limiting the programmatic builder interface... which leaves  identifier checking, which is relevant for parsing _and_ programmatic glyph building. Identifiers are barely used as of now, but could benefit from a builder checking things behind the scenes. Otherwise, the GlyphBuilder API provides no discernible advantage over stuffing objects into a Glyph directly.

I am tempted to rip out GlyphBuilder and move some of the responsibilities back into parsing. I think OutlineBuilder can stick around, though. Glyph-level identifier checking is desirable but needs some more thinking; until then, we can maybe leave it to the user and make sure we don't load or save invalid UFOs...
